version: '2.3'
services:
  notebook:
    container_name: deeplearning
    image: deeplearning-img
    #build: .
    labels:
      description: Python3 with tensorflow/keras using Jupyter Notebooks
      name: jupyter notebook 
    ports:
      - "8888:8888"
    volumes:
      - .:/usr/tf/notebooks
    # Run shell command for notebook on start 
    entrypoint: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root
    runtime: "nvidia"
